### ISSUE TITLE
Hashcode implementations of all command and related classes

### ISSUE THREAD

**Issue by suriruhani** [CS2103-AY1819S2-W13-3/main#207]
override along with equals() method to ensure code integrity.
The hashcode function should be sophisticated and non-trivial.

- [x] search

**Comment by ToonDragon** [comment]
Good implementation for the search feature, I will be working on the remaining functions that require this as well to make it more up to standard.  I managed to find a simple yet effective way to create hashcodes.

**Comment by suriruhani** [comment]
@DarrenDragonLee can try to use intellij's autogenerate feature to write an overriding hashcode() function, else can close this issue already

**Comment by case141** [comment]
agreed with @suriruhani

**Comment by ToonDragon** [comment]
After close examination of the codebase, it has been determined that the hashcode does not truly affect the functionality of the software presently or in the foreseeable future.  Therefore, a rudimentary hash function will suffice for the purposes of this program.
