### ISSUE TITLE
Issue with Undo command not being able to undo add or order

### ISSUE THREAD

**Issue by ToonDragon** [CS2103-AY1819S2-W13-3/main#235]
When trying to undo and add or order command, the command indicates there are no commands to undo despite the counter being stated as one.  

Noticed the issue was related to the undo command checking if both the current source manager and the deleted source manager (for the recycle bin functionality) were both being checked at once.

![image](https://user-images.githubusercontent.com/46807679/56090587-9ce86900-5ed6-11e9-938c-c2247211c119.png)

If either check failed, the undo command would fail stating that no commands were available to undo.  Add and order commands do not commit to the deleted source manager and thus will always trigger this condition.

Perhaps implementing an AND condition would help to solve the issue by making sure that only when both checks for commands failed, then the undo command would fail.

**Comment by case141** [comment]
Added an AND condition and also additional checks so that the undo and redo commands will not bug out if the commands only interacts with either the **Source Manager** or **Deleted Sources**. #234
