### ISSUE TITLE
As a user I would like to be able to view the past history of commands that I have made

### ISSUE THREAD

**Issue by case141** [CS2103-AY1819S2-W13-3/main#29]
So that I can recall what I have done in the past.

**Comment by DoItTomorrow** [comment]
There was already a history command, so I implemented a biblio command for 1.2 first instead.

**Comment by case141** [comment]
If thats the case please create a new issue for this milestone thanks.

**Comment by case141** [comment]
If thats the case please create a new issue and tag your PR to it.
